# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_version=0.161.0+26.3

# Mod Properties
mod_version=2.14
maven_group=me.dacubeking
archives_base_name=clientsidenoteblocks
# https://linkie.shedaniel.dev/dependencies?loader=fabric
modmenu_version=21.0.0-beta.1
cloth_config_version=26.3.158
